/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as ListSalonRouteImport } from './routes/list-salon'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiAdvisorRouteImport } from './routes/ai-advisor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonsIndexRouteImport } from './routes/salons.index'
import { Route as SalonsSalonIdRouteImport } from './routes/salons.$salonId'
import { Route as BookSalonIdRouteImport } from './routes/book.$salonId'

const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const ListSalonRoute = ListSalonRouteImport.update({
  id: '/list-salon',
  path: '/list-salon',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAdvisorRoute = AiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsIndexRoute = SalonsIndexRouteImport.update({
  id: '/salons/',
  path: '/salons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsSalonIdRoute = SalonsSalonIdRouteImport.update({
  id: '/salons/$salonId',
  path: '/salons/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSalonIdRoute = BookSalonIdRouteImport.update({
  id: '/book/$salonId',
  path: '/book/$salonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/list-salon': typeof ListSalonRoute
  '/memberships': typeof MembershipsRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$salonId': typeof SalonsSalonIdRoute
  '/salons/': typeof SalonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/list-salon': typeof ListSalonRoute
  '/memberships': typeof MembershipsRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$salonId': typeof SalonsSalonIdRoute
  '/salons': typeof SalonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-advisor': typeof AiAdvisorRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/list-salon': typeof ListSalonRoute
  '/memberships': typeof MembershipsRoute
  '/my-bookings': typeof MyBookingsRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/book/$salonId': typeof BookSalonIdRoute
  '/salons/$salonId': typeof SalonsSalonIdRoute
  '/salons/': typeof SalonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-advisor'
    | '/auth'
    | '/gallery'
    | '/list-salon'
    | '/memberships'
    | '/my-bookings'
    | '/owner-dashboard'
    | '/book/$salonId'
    | '/salons/$salonId'
    | '/salons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-advisor'
    | '/auth'
    | '/gallery'
    | '/list-salon'
    | '/memberships'
    | '/my-bookings'
    | '/owner-dashboard'
    | '/book/$salonId'
    | '/salons/$salonId'
    | '/salons'
  id:
    | '__root__'
    | '/'
    | '/ai-advisor'
    | '/auth'
    | '/gallery'
    | '/list-salon'
    | '/memberships'
    | '/my-bookings'
    | '/owner-dashboard'
    | '/book/$salonId'
    | '/salons/$salonId'
    | '/salons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAdvisorRoute: typeof AiAdvisorRoute
  AuthRoute: typeof AuthRoute
  GalleryRoute: typeof GalleryRoute
  ListSalonRoute: typeof ListSalonRoute
  MembershipsRoute: typeof MembershipsRoute
  MyBookingsRoute: typeof MyBookingsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  BookSalonIdRoute: typeof BookSalonIdRoute
  SalonsSalonIdRoute: typeof SalonsSalonIdRoute
  SalonsIndexRoute: typeof SalonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-salon': {
      id: '/list-salon'
      path: '/list-salon'
      fullPath: '/list-salon'
      preLoaderRoute: typeof ListSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-advisor': {
      id: '/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/ai-advisor'
      preLoaderRoute: typeof AiAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/': {
      id: '/salons/'
      path: '/salons'
      fullPath: '/salons/'
      preLoaderRoute: typeof SalonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons/$salonId': {
      id: '/salons/$salonId'
      path: '/salons/$salonId'
      fullPath: '/salons/$salonId'
      preLoaderRoute: typeof SalonsSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$salonId': {
      id: '/book/$salonId'
      path: '/book/$salonId'
      fullPath: '/book/$salonId'
      preLoaderRoute: typeof BookSalonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAdvisorRoute: AiAdvisorRoute,
  AuthRoute: AuthRoute,
  GalleryRoute: GalleryRoute,
  ListSalonRoute: ListSalonRoute,
  MembershipsRoute: MembershipsRoute,
  MyBookingsRoute: MyBookingsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  BookSalonIdRoute: BookSalonIdRoute,
  SalonsSalonIdRoute: SalonsSalonIdRoute,
  SalonsIndexRoute: SalonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
